### ISSUE TITLE
Incompatibility with recent PyPDF2 versions

### ISSUE THREAD

**Issue by jannisborn** [BjoernLudwigPTB/pyxml2pdf#10]
Currently upon a fresh installation, one gets:
```
from pyxml2pdf.core.post_processor import PostProcessor
  File "/Users/jannisborn/anaconda3/envs/paperscraper/lib/python3.8/site-packages/pyxml2pdf/core/post_processor.py", line 5, in <module>
    from PyPDF2.pdf import PageObject, PdfFileReader, PdfFileWriter  # type: ignore
ModuleNotFoundError: No module named 'PyPDF2.pdf'
```

Quick fix: We have to pin the PyPDF2 version.
The alternative is a code refactor to reflect all the great recent changes in that package

**Comment by jannisborn** [comment]
Hi @BjoernLudwigPTB,
thanks for the quick feedback. There's no rush on my side to get this integration ready soon, so please take your time to integrate the lates changes in PyPDF2

**Comment by BjoernLudwigPTB** [comment]
Thanks @jannisborn for the heads up regarding the PyPDF2 breaking change!

**Comment by jannisborn** [comment]
Great! Thanks for the instant fix @BjoernLudwigPTB 🚀

**Comment by BjoernLudwigPTB** [comment]
In case you have any questions regarding the use of the package I would be very happy to assist with whatever use case you are trying to tackle… and anyway I am very curious, whether you are successful in pyxml2pdf's application or what problems you are facing. So feel free to [start a discussion](https://github.com/BjoernLudwigPTB/pyxml2pdf/discussions) in case there is anything to share.
